version: 2
jobs:
  node:
    working_directory: ~/demo-react-native
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: jest tests
          command: |
            yarn run test


workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
